### ISSUE TITLE
Error when running bi_ripleys_k with only one marker

### ISSUE THREAD

**Issue by dBenedek** [FridleyLab/spatialTIME#9]
Hi,

This line fails when I have only one marker (mnames), probably because the `expand.grid` function needs a character vector longer than 1.

https://github.com/FridleyLab/spatialTIME/blob/1c85d8e9083e1c4333f66f89ef8eb4e52713a5e7/R/bi_ripleys_k.R#L105

Best,
Benedek

**Comment by ACSoupir** [comment]
Hi, Bendek.

Bivariate Ripley's K requires 2 markers (Bi = 2). If you are only supplying a single marker, it won't work as you are then just running univariate clustering. In this case, stick with `ripleys_k` to avoid this issue.

-acs

**Comment by dBenedek** [comment]
> Hi, Benedek.
> 
> Bivariate Ripley's K requires 2 markers (Bi = 2). If you are only supplying a single marker, it won't work as you are then just running univariate clustering. In this case, stick with `ripleys_k` to avoid this issue.
> 
> -acs

Thanks!

(I thought that bivariate means 2 different cell types, not markers.)

**Comment by dBenedek** [comment]
> Hi, Benedek.
> 
> Bivariate Ripley's K requires 2 markers (Bi = 2). If you are only supplying a single marker, it won't work as you are then just running univariate clustering. In this case, stick with `ripleys_k` to avoid this issue.
> 
> -acs

Hello,

My further question related to my last one is what happens if I have one marker but two cell types? In this case, I would like to quantify the clustering between the two cell types (only for positives), and not within one cell type. Should I split the marker by cell type?

I appreciate your help.

Benedek

**Comment by oospina** [comment]
Hi Benedek,
I'll jump into the discussion, hoping I will not confuse things.
spatialTIME does not know about cell types or markers in the biological sense. It measures the degree of clustering for points in the 2D space (translated to biology these could be cell types, cells expressing (or not) markers, cell states, etc). As long as you can classify your cells and count those classes, you can apply the functions. 
The difference between bivariate and univariate Ripley's K is the number of classes involved in the calculation (one for univariate, and two for bivariate). For practical purposes, the classes are the 1/0 columns in the data frames of your `spatial_list`.
If I understood well you question, you just need to put each of your cell types in two columns of the `spatial_list`. Each row of the data frames will say if a given cell is (1) or not (0) one of the cell types.

Oscar

**Comment by dBenedek** [comment]
> Hi Benedek, I'll jump into the discussion, hoping I will not confuse things. spatialTIME does not know about cell types or markers in the biological sense. It measures the degree of clustering for points in the 2D space (translated to biology these could be cell types, cells expressing (or not) markers, cell states, etc). As long as you can classify your cells and count those classes, you can apply the functions. The difference between bivariate and univariate Ripley's K is the number of classes involved in the calculation (one for univariate, and two for bivariate). For practical purposes, the classes are the 1/0 columns in the data frames of your `spatial_list`. If I understood well you question, you just need to put each of your cell types in two columns of the `spatial_list`. Each row of the data frames will say if a given cell is (1) or not (0) one of the cell types.
> 
> Oscar

Thank you!

Exactly, what I did is I have two columns in my `spatial_list` object (`celltypeA_markerX+` and `celltypeB_markerX+`), and when running `bi_ripleys_k` I simply specified `mnames=c("celltypeA_markerX", "celltypeB_markerX")`.
And this works perfectly.
